### ISSUE TITLE
The version blocks are sorted alphabetically instead of versions being sorted numerically

### ISSUE THREAD

**Issue by Jakuje** [ansasaki/abimap#88]
With recent libssh update, we got released `LIBSSH_4_10_0`, which is in generated map files sorted at top of the file instead of to the bottom.

I assume this is caused by simple comparsion of the labels without taking care of multi-digit numbers.

I can try to submit a PR, but not sure when I will get my hands free to do so.

**Comment by ansasaki** [comment]
Thanks for reporting this. I also have to find the time to dedicate to the project. I think the issue you pointed out should be somehow easy to fix. I cannot promise that I will fix this soon, but I'll add to my todo list.
